version: '3.8'

services:
  app:
    image: exs
    container_name: exs-container

    build:
      context: .
      dockerfile: dockerfile

    ports:
      - "8443:8443"

    env_file:
      - .env

    volumes:
      - ./logs:/app/logs
      - ./user.db:/app/user.db

    restart: always
