# ===============================
# 📦 Application Configuration
# ===============================
spring.application.name=PFC_Projeto
server.servlet.context-path=/

# Render define a porta AUTOMATICAMENTE
server.port=${PORT}

# ===============================
# 🗄️ Database Configuration (RENDER)
# ===============================
spring.datasource.url=${DATABASE_URL_JDBC}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Em PostgreSQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# 🔐 JWT Security Configuration
# ===============================
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
jwt.cookie.name=token

# ===============================
# 📧 Email Configuration
# ===============================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.base-url=${APP_BASE_URL}


# ===============================
# 🧾 Logging Configuration
# ===============================
logging.file.name=./logs/application.log
logging.level.root=WARN
logging.level.umc.exs=INFO
